name: movie_finder
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.2

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.7
  bloc_test: ^9.1.5
  auto_route_generator: ^7.3.2

flutter:

  assets:
    - assets/images/image_placeholder.png

  uses-material-design: true
