name: movie_finder
description: "Find movies based on popularity or ratings and add them to a watch list. Watch list requires TMDB account."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.2

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  auto_route: ^7.8.4
  shared_preferences: ^2.2.2
  rxdart: ^0.27.7
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.7
  bloc_test: ^9.1.5
  auto_route_generator: ^7.3.2

flutter:

  assets:
    - assets/images/image_placeholder.png
    - assets/images/tmdb_logo.png
    - assets/images/1.5x/tmdb_logo.png
    - assets/images/2.0x/tmdb_logo.png
    - assets/images/3.0x/tmdb_logo.png
    - assets/images/4.0x/tmdb_logo.png

  fonts:
    - family: AbeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

  uses-material-design: true
